### ISSUE TITLE
Document Gorjun DB schema and upgrade process

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/cdn#145]
To have people contribute to Gorjun we need to document:

* how the database is structured?
* how to extract, and load to new db?
* what happens with db changes?
* what's the rule for introducing incompatible changes, and do we need to massage the data?

Something is needed asap to make sure we have this information. Diagrams are nice too :).

**Comment by soffokl** [comment]
First of all, we are using BoltDB that is key-value storage 

On the top level, we have following buckets: 
* **MyBucket** (dumb name, I know) - store information about all files in Gorjun. _**Here key - is a file UUID.**_ 
* **Users** - store all users registered in the system. **_Key is a username, the value is a bucket with_** multiple GPG-keys. 
* **SearchIndex** - store a search index for fast accessing artifacts. **_Key - filename, value - bucket with files UUIDs._** 
* **Tokens** - store authentication tokens for user sessions. **_Key - token, value bucket with username and date of creation._** 
* **AuthID** - store AuthID(random string) that user should sign to get token. **_Key - authID, value - username._**
* **Tags** - another search index that is used to group templates by tags. _**Key - tag, value - template UUIDs**_

**Comment by soffokl** [comment]
**MyBucket**
The following fields can be added to this bucket: 


**Hash** - bucket that contains(md5 and sha256);
**Size** - file size
**Name** - file name
**Tags** - bucket that contains tags 
**Owner** - bucket that contains file oweners 
**Parent** - parent of the subutai template
**Version** - file version
**Filename** - file name
**Prefsize** - preferred 
**Signature** - bucket that contains user signatures 
**Description** - description of the file
**Architecture** - architecture of the template or dev file

**Comment by emli** [comment]
Database Structure Diagrams. Blue cells are keys.

**MyBucket**
![mybucket](https://user-images.githubusercontent.com/5517490/32764439-b36e9e1c-c92f-11e7-9ff2-e4259138bc16.png)


**Users**
![users](https://user-images.githubusercontent.com/5517490/32764430-a3007636-c92f-11e7-8b06-e3ea28b6ebf2.png)

**SearchIndex**
![searchindex](https://user-images.githubusercontent.com/5517490/32764459-d32cbe78-c92f-11e7-8f44-e5ed4ad7c501.png)

**Tokens**
![tokens](https://user-images.githubusercontent.com/5517490/32764487-ed844796-c92f-11e7-8141-cc8183413341.png)

**AuthID**
![authid](https://user-images.githubusercontent.com/5517490/32764503-0621b45a-c930-11e7-971e-c7690854aa61.png)

**Tags**
![tags](https://user-images.githubusercontent.com/5517490/32764608-b45f4c9e-c930-11e7-9cfc-44924ba3d590.png)

**Comment by akarasulu** [comment]
This is too confusing. Can’t you just use a simple ER diagram?
Why did you do it like this?

**Comment by emli** [comment]
![ready](https://user-images.githubusercontent.com/5517490/32818664-d029e574-c9ee-11e7-9b86-60ce3121ae9f.png)

**Comment by emli** [comment]
We have this document https://github.com/subutai-io/cdn/wiki/Database
