### ISSUE TITLE
Extend support for tags to all artifact types

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/cdn#171]
Right now tags are only supported for templates. We can use tags for all the other artifact types and its a really small change to allow this feature to extend to the other raw, and apt types.

**Comment by AlinaPenkina** [comment]
It works with raw files, for apt files downloading works in this format: https://mastercdn.subutai.io:8338/kurjun/rest/apt/subutai-control-center-master.deb

**Comment by AlinaPenkina** [comment]
Fixed on master

**Comment by kurmanbekova6** [comment]
Fixed on prod
