### ISSUE TITLE
Wrong deb file can fail build of management template

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/cdn#173]
Management template build failed due to presence of extra package in our APT repo on CDN.
However the APT repo is exposed for users and anyone can upload any package there.
We need to investigate what exactly caused the apt-get update and install commands to fail.
Check file attributes and proper registration in APT index

**Comment by emli** [comment]
@Dilshat can check this issue https://github.com/subutai-io/gorjun/issues/124

**Comment by etursunbaev** [comment]
This is not actual anymore
