### ISSUE TITLE
Gorjun don't list empty repositories, instead returns 404 Not found

### ISSUE THREAD

**Issue by marcoarthur** [subutai-io/cdn#187]
Test results:
<pre>
ok 1 - use Gorjun;
# Test Data Information: 
# 
# User Name: tester
# User Email: tester@gmail.com
# PGP Key:
# -----BEGIN PGP PUBLIC KEY BLOCK-----
# 
# mQENBFoYPuoBCACtzSfHf1FSVVerB00zx/Zhxlbey87UZ+Q/MC8GSYpzHdS27X26
# C2thj0fmWapCk/k6vQL6hRXvfKoAUr6tWbGsfiXgGU3o1cLxXNI/v6TBv2E5Mvqk
# gPDSxFC+hU9ds0wP0M5SRf7xNl2zlYcgNocxEiLwSx2lnMPwhhy8z5d4AJMGKZfu
# smbeZUf//usLf8nFvdLgM2+JWA48l9CbunxufuPy4c5den81coq1s8TFX+n1Kx+Y
# BtDQ8rmM4jRG/aMUChCqKfjNMGlTRHP5Zq77e++uo7bsdP0ljD4vmEtbqyIpGCaM
# IlKYNP0voTnzsXxvPO7t9qgTNiCCMChIidEpABEBAAG0MlRlc3RlciAod2l0aCBz
# dHVwaWQgcGFzc3BocmFzZSkgPHRlc3RlckBnbWFpbC5jb20+iQFOBBMBCAA4FiEE
# 1PTzXOs4SyWNBLaK//hAyy0hbyQFAloYPuoCGwMFCwkIBwIGFQgJCgsCBBYCAwEC
# HgECF4AACgkQ//hAyy0hbySesgf/XJ+l4vcyunUscG7htX5/uTV/uRcVr/8+coI2
# 92VsV9Sz0QFtC/odLrTO6rdzbl5MZgw//iMec56oLYhhvs6+0KqAA1NtgPeQNxPZ
# D+Szwp5NwP0ReInYFRvIceu86WPOGUBmrkqaDc/YdYAXVuObmvVXq1xUJbv4I073
# wUGbTJJrrB8bdlQBYO8yx2yPDWLB8zN2qjTWTzKiLvgcDvNX7GMSDlj3u4yUUHBz
# lN4lkJHCNzjyNLRzSBB2PFfCTFDajaJd6/oXswYNqs9JiQO2Gyw1YyVGag81G3k3
# zeCbFk79lKWPfDtAyAJaic5LVu64O5OCH1H+SnKD2sJcoSLwpbkBDQRaGD7qAQgA
# 8cT9XlErMQhb/dZpS/m97jjHsM7RFgGNG3n7e6UHrAlt/Wzkv4mvRTA+HdxBywxX
# KRaoDkq1AhmdWLZ8qnouCDvBGDaBKQSwIUrLDZYkBiH1zNAFQBC3yJUBtX0HDJry
# I+2b4/zlMLC+rbCxYdkyY3cQ1FEvkJEzsuWqRnkgAlrTLfZssVKHIbENKAqIc+wG
# YDsftZCN8R+VSi0oO5CzEYMwmaffyYov99PjtTIHxPRKUcs9EM9PVGpzle5Hvb62
# UMttb7Xo2TTDDj7TlECxxtlFTzX75l60zAQ0TYMP9rlxH0Ap1RspDNO0tTVoeAgJ
# x2pSvunpOFug7O/VGQcEhwARAQABiQE2BBgBCAAgFiEE1PTzXOs4SyWNBLaK//hA
# yy0hbyQFAloYPuoCGwwACgkQ//hAyy0hbyRD8gf9G4ACTEJ1WjJ6cDY5bPeY8XMk
# /2XEeiNYvtfQtJQg6034r17jL7080iUtcLaPVe5n7PiuJA7dY4AnmN7k8D3fLtVS
# 17x2+NEof6uGJNOQoGXp0fWrQ+NbxCAyADIU11XWGviF3vQwDzwapArnTJTMaE8w
# pMteledI8PynWigfDlQRUoX5YUxMXDFRpPa6nR+pvTt5210MJWgSCqb992+5GIrn
# n0J/oTbBsJhIXbzwmpDJhoM7I61X3pYlg6HZHRCjjWEUJeE0QR0+jkHzH7zEPa9t
# As75s2Xb4x2h1+Bjv0g8AL1OycXgGMiIlAVwVWE6aVRzt0oBVXQxnZGtD166+w==
# =+loE
# -----END PGP PUBLIC KEY BLOCK-----
# 
ok 2 - Register was done
# Name: tester
# PGP key: -----BEGIN PGP PUBLIC KEY BLOCK-----
# 
# mQENBFoYPuoBCACtzSfHf1FSVVerB00zx/Zhxlbey87UZ+Q/MC8GSYpzHdS27X26
# C2thj0fmWapCk/k6vQL6hRXvfKoAUr6tWbGsfiXgGU3o1cLxXNI/v6TBv2E5Mvqk
# gPDSxFC+hU9ds0wP0M5SRf7xNl2zlYcgNocxEiLwSx2lnMPwhhy8z5d4AJMGKZfu
# smbeZUf//usLf8nFvdLgM2+JWA48l9CbunxufuPy4c5den81coq1s8TFX+n1Kx+Y
# BtDQ8rmM4jRG/aMUChCqKfjNMGlTRHP5Zq77e++uo7bsdP0ljD4vmEtbqyIpGCaM
# IlKYNP0voTnzsXxvPO7t9qgTNiCCMChIidEpABEBAAG0MlRlc3RlciAod2l0aCBz
# dHVwaWQgcGFzc3BocmFzZSkgPHRlc3RlckBnbWFpbC5jb20+iQFOBBMBCAA4FiEE
# 1PTzXOs4SyWNBLaK//hAyy0hbyQFAloYPuoCGwMFCwkIBwIGFQgJCgsCBBYCAwEC
# HgECF4AACgkQ//hAyy0hbySesgf/XJ+l4vcyunUscG7htX5/uTV/uRcVr/8+coI2
# 92VsV9Sz0QFtC/odLrTO6rdzbl5MZgw//iMec56oLYhhvs6+0KqAA1NtgPeQNxPZ
# D+Szwp5NwP0ReInYFRvIceu86WPOGUBmrkqaDc/YdYAXVuObmvVXq1xUJbv4I073
# wUGbTJJrrB8bdlQBYO8yx2yPDWLB8zN2qjTWTzKiLvgcDvNX7GMSDlj3u4yUUHBz
# lN4lkJHCNzjyNLRzSBB2PFfCTFDajaJd6/oXswYNqs9JiQO2Gyw1YyVGag81G3k3
# zeCbFk79lKWPfDtAyAJaic5LVu64O5OCH1H+SnKD2sJcoSLwpbkBDQRaGD7qAQgA
# 8cT9XlErMQhb/dZpS/m97jjHsM7RFgGNG3n7e6UHrAlt/Wzkv4mvRTA+HdxBywxX
# KRaoDkq1AhmdWLZ8qnouCDvBGDaBKQSwIUrLDZYkBiH1zNAFQBC3yJUBtX0HDJry
# I+2b4/zlMLC+rbCxYdkyY3cQ1FEvkJEzsuWqRnkgAlrTLfZssVKHIbENKAqIc+wG
# YDsftZCN8R+VSi0oO5CzEYMwmaffyYov99PjtTIHxPRKUcs9EM9PVGpzle5Hvb62
# UMttb7Xo2TTDDj7TlECxxtlFTzX75l60zAQ0TYMP9rlxH0Ap1RspDNO0tTVoeAgJ
# x2pSvunpOFug7O/VGQcEhwARAQABiQE2BBgBCAAgFiEE1PTzXOs4SyWNBLaK//hA
# yy0hbyQFAloYPuoCGwwACgkQ//hAyy0hbyRD8gf9G4ACTEJ1WjJ6cDY5bPeY8XMk
# /2XEeiNYvtfQtJQg6034r17jL7080iUtcLaPVe5n7PiuJA7dY4AnmN7k8D3fLtVS
# 17x2+NEof6uGJNOQoGXp0fWrQ+NbxCAyADIU11XWGviF3vQwDzwapArnTJTMaE8w
# pMteledI8PynWigfDlQRUoX5YUxMXDFRpPa6nR+pvTt5210MJWgSCqb992+5GIrn
# n0J/oTbBsJhIXbzwmpDJhoM7I61X3pYlg6HZHRCjjWEUJeE0QR0+jkHzH7zEPa9t
# As75s2Xb4x2h1+Bjv0g8AL1OycXgGMiIlAVwVWE6aVRzt0oBVXQxnZGtD166+w==
# =+loE
# -----END PGP PUBLIC KEY BLOCK-----
ok 3 - Get quota value done
# {"left":2147483648,"quota":2147483648,"used":0}
ok 4 - Token got
# bf575d5658aaf0b71f71b1e0d75d9931acf013c7c3724fbd4da58395eff7c41a
Error sending request, got this: **Not Found** at /home/itaipu/tools/perl5/gorjun/t/test.t line 78.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 4.
</pre>
sending a request for http://127.0.0.1:8080/kurjun/rest/raw/info into an empty repository, same behavior for **template** and **apt**

**Comment by Dilshat** [comment]
Please be aware that Kurjun should return 404 for Packages.* files

**Comment by emli** [comment]
CDN should return response `Not Found` because jenkins files that uses this rest. https://github.com/subutai-io/peer-os/blob/master/Jenkinsfile#L190
