### ISSUE TITLE
Test templates for correctness before uploading

### ISSUE THREAD

**Issue by emli** [subutai-io/cdn#217]
For example openssh-server should installed on templates so user can ssh to container

**Comment by Shahrizada** [comment]
You need to also make sure existing templates are working.

**Comment by crioto** [comment]
@emli please describe this issue in more details

**Comment by emli** [comment]
This issue created before when we had some broken templates -- we couldn't ssh to container  because inside template we hadn't got ` openssh-server` .

**Comment by crioto** [comment]
After removing docker-based templates this issue is not longer required.

**Comment by AlinaPenkina** [comment]
I am closing this issue due it is not actually anymore.
