### ISSUE TITLE
Packages file providing old information for some apt file

### ISSUE THREAD

**Issue by emli** [subutai-io/cdn#249]
![image](https://user-images.githubusercontent.com/5517490/36422970-595243a8-1668-11e8-9279-3a6064b11bf3.png)

It happens with old apt files. For new apt files, it works correctly. In Packages file there are old info about apt.  We should update Packages file.

**Comment by AlinaPenkina** [comment]
Need to wait after uploading 6 hours to update info in CDN.

**Comment by AlinaPenkina** [comment]
Fixed on master.

**Comment by amol4anoff** [comment]
Done in production.
