### ISSUE TITLE
When artifacts uploaded to APT repo, deb files storing without extension.

### ISSUE THREAD

**Issue by emli** [subutai-io/cdn#250]
**How to generate Release file?**

`dpkg-scanpackages . /dev/null | tee Packages | gzip > Packages.gz`
`apt-ftparchive release . > Release`

`dpkg-scanpackages . /dev/null | tee Packages | gzip > Packages.gz` - scans all files with deb extension.

Currently, command `dpkg-scanpackages` can't find deb files, because gorjun omit extensions,so it can't find files with deb extension.

So for `dpkg-scanpackages` it's needed to provide file with extension deb in file system.

Also there "old" files , this means they uploaded before, need find way add deb extension to "old" files

**Comment by AlinaPenkina** [comment]
I don't have access to server to check this issue.
