### ISSUE TITLE
When no owner is specified, search template only within verified ones

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/cdn#259]
When artifact (info/file) is requested from CDN only by name, it should be searched within verified templates only and if not found then return NOT FOUND 404. 
Verified templates belong to owner SUBUTAI, JENKINS

**Comment by emli** [comment]
How to reproduce?

1)https://devcdn.subut.ai:8338/kurjun/rest/template/list?name=debian-stretch
2)https://devcdn.subut.ai:8338/kurjun/rest/template/list?name=debian-stretch&verified=true

The second URL should return the latest template version

**Comment by Dilshat** [comment]
both RESTs should return verified. Why? Because if there many templates with the same name of different owners and some of them have the same latest version , which one should it give?

**Comment by emli** [comment]
Also one more example https://mastercdn.subut.ai:8338/kurjun/rest/template/info?name=debian-stretch, this rest should return , verified owner

**Comment by Dilshat** [comment]
If user passes token (i.e. user is authenticated) then CDN might search within the users templates and then only fallback to verified

**Comment by AlinaPenkina** [comment]
Fixed on master.

**Comment by amol4anoff** [comment]
Please release to production @emli @Dilshat

**Comment by AlinaPenkina** [comment]
Done
