### ISSUE TITLE
Properly remove artifacts remaining on filesystem after deleting from database

### ISSUE THREAD

**Issue by emli** [subutai-io/cdn#270]
https://github.com/subutai-io/cdn/issues/215#issuecomment-366418440
https://github.com/subutai-io/cdn/issues/215#issuecomment-369565119

**Comment by amol4anoff** [comment]
@emli how to reproduce?

**Comment by amol4anoff** [comment]
Failed:
added 2 files in raw, then removed second file, then removed first file. System showed that first file is still in filesytem.

**Comment by AlinaPenkina** [comment]
Fixed on master.

**Comment by amangeldizhusubaliev** [comment]
fixed on prod.
