### ISSUE TITLE
User can't delete Apt file from CDN

### ISSUE THREAD

**Issue by AlinaPenkina** [subutai-io/cdn#273]
When I tried to delete Apt file from CDN, this error message appeared:
![image.png](https://images.zenhubusercontent.com/5a27a7008a75884b908a0e36/f8d6ed5e-d448-41df-a085-f88d6e0c7f78)
After reloading by pushing "Reload" button, all my .deb files disappeared.

**Comment by AlinaPenkina** [comment]
When I uploaded Apt file it doesn't appear in my own files. I can't find it by using filter "Mine".

**Comment by AlinaPenkina** [comment]
I can delete the APT file, but if I repeat this procedure several times, it shows again this error. But it related with cash, so @emli has another issue about cleaning cash.

**Comment by AlinaPenkina** [comment]
@emli Need Admin rights to reproduce this issue on production.

**Comment by kurmanbekova6** [comment]
There's  still several broken files.

**Comment by kurmanbekova6** [comment]
I still face with this issue on production.

**Comment by ibragim13kz** [comment]
@azretkenzhaliev Why did you move it to Done again?

**Comment by AlinaPenkina** [comment]
I don't face this problem on production.
