### ISSUE TITLE
Integrate additional info to template metadata

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/cdn#298]
We have to add the following properties into the template **config** file:
- **subutai.template** - name of template
- **subutai.template.owner** - owner of template
- **subutai.parent.owner** - owner of parent template
- **subutai.parent.version** - version of parent template

We need to update the hashsums of templates afterwards

**Comment by amol4anoff** [comment]
Fixed.

**Comment by amol4anoff** [comment]
Fixed in prod.
