### ISSUE TITLE
Separate "../list" from "../info" REST

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/cdn#299]
Currently CDN has 2 rest endpoints that has the same functionality `../list` and `../info`

However `../info` must return information about a single template. The logic behind should be as described here https://github.com/subutai-io/cdn/wiki/Fetching-template-info-by-name

And `../list` must return a set of template metadata (0-N) that are optionally filtered according to the passed parameters. The logic behind should be as described here https://github.com/subutai-io/cdn/wiki/Listing-templates

**Comment by azretkenzhaliev** [comment]
ETA: Friday, May 18, 2018, 15:00 ^

**Comment by AlinaPenkina** [comment]
Fixed on master.

**Comment by kurmanbekova6** [comment]
Fixed on prod.
