### ISSUE TITLE
Check config file of uploaded templates

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/cdn#303]
We need to check the following properties of the uploaded template:
1. **subutai.parent** - parent template name of the uploaded template
2. **subutai.parent.owner** - parent template owner of the uploaded template
3. **subutai.parent.version** - parent template version of the uploaded template
4. **subutai.template.version** - version of the uploaded template
5. **subutai.template** - name of the uploaded template
6. **subutai.template.owner**  - owner of the uploaded template

- These properties must be present and non empty.
- CDN must ensure that the specified template (subutai.template + subutai.template.owner ) does not already exist. User may upload a higher version, replace existing but must not be able to push lower version
- CDN must ensure that the specified subutai.template.owner is the same as the uploading user
- CDN must ensure that parent(foo)=foo or parent(foo)=existing template (existing means that the specified parent template (subutai.parent + subutai.parent.owner + subutai.parent.version) exists.)

**Comment by Dilshat** [comment]
Also template names and owners must be checked against regular expression `[^a-zA-Z0-9._-]`.
Version must be checked against ``

**Comment by amol4anoff** [comment]
Done.

**Comment by amol4anoff** [comment]
Now need to release to production.

**Comment by TerGunter** [comment]
fixed on prod
