### ISSUE TITLE
Cleanup unused files on CDN filesystem

### ISSUE THREAD

**Issue by emli** [subutai-io/cdn#333]
Since cdn has https://github.com/subutai-io/cdn/issues/270 this issue , there lot of garbage files on cdn.

**Comment by emli** [comment]
Clean 60% - 70% unused files on devcdn

**Comment by amol4anoff** [comment]
@emli how to reproduce?

**Comment by AlinaPenkina** [comment]
Fixed on master.

**Comment by amangeldizhusubaliev** [comment]
fixed on prod.
