### ISSUE TITLE
Template disappears after uploading a same template to CDN

### ISSUE THREAD

**Issue by ibragim13kz** [subutai-io/cdn#360]
Steps to reproduce: 
1. Download `apache 2` template from CDN. 
2. Upload it to CDN — there will be an error `failed to upload`. 
3. Then download it again. You'll get this: 
![screenshot_3](https://user-images.githubusercontent.com/33474101/40051810-df454ff0-585d-11e8-9e3d-1cc56b4ba6c3.png)

**Comment by AlinaPenkina** [comment]
I still face exactly the same error.

**Comment by azretkenzhaliev** [comment]
Done on sysnet.

**Comment by AlinaPenkina** [comment]
Fixed on master.
