### ISSUE TITLE
can't download the template on dev

### ISSUE THREAD

**Issue by sarage** [subutai-io/cdn#361]
![screenshot from 2018-05-17 15-41-27](https://user-images.githubusercontent.com/9797503/40171776-231d2e14-59ee-11e8-90c8-719e6043497b.png)
![screenshot from 2018-05-17 15-38-30](https://user-images.githubusercontent.com/9797503/40171777-2345d24c-59ee-11e8-9a43-0578a8c6f0e3.png)

**Comment by AlinaPenkina** [comment]
Fixed on dev and master.

**Comment by ibragim13kz** [comment]
Fixed.
