### ISSUE TITLE
The Templates without the Owners

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/cdn#368]
There are some of the old templates in the CDN code without the owners. 

It should be so that the templates that will be created in the future would not have this trouble with missing owners. 

Goal: Deleting the old templates and making sure to not have this issue in the future.

**Comment by azretkenzhaliev** [comment]
Done on sysnet.

**Comment by AlinaPenkina** [comment]
Fixed on master.

**Comment by ibragim13kz** [comment]
Done in Production.
