### ISSUE TITLE
Enhance search by tags

### ISSUE THREAD

**Issue by azretkenzhaliev** [subutai-io/cdn#375]
Currently, the Tags bucket is not used. We can use it in the following way to enhance search by tags (currently search is done by iterating through all files, which is ineffective):

* when uploading files (for instance, `file1`, `file2`, `file3`) with tags (for example, `tag1, tag2`, `tag1, tag3`, and `tag2, tag3` respectively) we will create respective keys in Tags bucket ( `(key: tag1, value: [file1, file2])`, `(key: tag2, value: [file1, file3])`, `(key: tag3, value: [file2, file3])` )
* when searching *NON-STRICTLY* for files with tags (for example, `[tag1, tag3]`) we will *UNION* the values of respective tags (for example, union `(key: tag1, value: [file1, file2])` and `(key: tag3, value: [file2, file3])` -> `[file1, file2, file3]`)
* when searching *STRICTLY* for files with tags (for example, `[tag1, tag3]`) we will *INTERSECT* the values of respective tags (for example, union `(key: tag1, value: [file1, file2])` and `(key: tag3, value: [file2, file3])` -> `[file2]`)

**Comment by azretkenzhaliev** [comment]
Done.

**Comment by AlinaPenkina** [comment]
Fixed on master.

**Comment by kurmanbekova6** [comment]
Fixed
