### ISSUE TITLE
Inability of .deb files to be downloaded from apt repository

### ISSUE THREAD

**Issue by Almansherov** [subutai-io/cdn#395]
Currently downloading .deb files from *apt* repository is not working. 
Need to fix it.

**Comment by AlinaPenkina** [comment]
We need to clean old APT files, because user can't download them. New files download correctly.

**Comment by kurmanbekova6** [comment]
There's still several broken files.

**Comment by AlinaPenkina** [comment]
There is another issue related with cleaning of broken file. #368
