### ISSUE TITLE
Update list endpoint according to recent changes in logic

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/cdn#400]
We need to adjust logic of `../list` endpoint according to recent changes in https://github.com/subutai-io/cdn/wiki/Listing-templates

Namely:
**../list?owner={owner}&token={token}**
```4. Lists all public templates of the specified owner + the private templates of the specified owner that are shared with the token holder```

**Comment by azretkenzhaliev** [comment]
Started working on the issue on May 22, 12:50.

**Comment by AlinaPenkina** [comment]
Fixed on master.

**Comment by kurmanbekova6** [comment]
Fixed on prod
